site_name: 90.CL
site_url: https://90.cl/

nav:
    - inicio: index.md
    - documentos: docs.md
    - sats: sats.md

theme:
    name: terminal
    custom_dir: overrides
    palette: dark
    features:
        hide: side_toc

markdown_extensions:
  - toc:
      permalink: " #"
